### ISSUE TITLE
Error adding service endpoint to DID

### ISSUE THREAD

**Issue by AnthonyRonning** [veres-one/did-veres-one#47]
Playing around with VeresOne to try to create a DID for us to use, which will require some service endpoints. I've run into a client error sending the did document to the Veres one blockchain (using the interop one, which I've redacted from the snippets in case that was supposed to be private). 

Error: 
```
(node:12416) UnhandledPromiseRejectionWarning: NetworkError: Error sending document.
    at WebLedgerClient.sendDocument (/Users/anthony/Dev/Repos/did-test/node_modules/web-ledger-client/lib/WebLedgerClient.js:253:21)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async VeresOne.send (/Users/anthony/Dev/Repos/did-test/node_modules/did-veres-one/lib/VeresOne.js:243:22)
    at async VeresOne.register (/Users/anthony/Dev/Repos/did-test/node_modules/did-veres-one/lib/VeresOne.js:188:5)
    at async test (/Users/anthony/Dev/Repos/did-test/did-test-create-service.js:27:32)
(node:12416) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:12416) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Having a debugger on `WebLedgerClient`, the response error looks to be `400 | ValidationError | "The input is invalid"` 

The full request document looks to be like
```
{
  "@context": "https://w3id.org/webledger/v1",
  "creator": "https://REDACTED/consensus/continuity2017/voters/z6MktdvC8wTVN2Rkkqiivdc95eih5EJrcu8jC4uKh1FGvhvx",
  "type": "CreateWebLedgerRecord",
  "record": {
    "@context": [
      "https://w3id.org/did/v0.11",
      "https://w3id.org/veres-one/v1"
    ],
    "id": "did:v1:test:nym:z6MkiUBCV4WG4ciU5vPq2ExK6AUUT5KxU7BYH6wW5dsSBUY4",
    "authentication": [
      {
        "id": "did:v1:test:nym:z6MkiUBCV4WG4ciU5vPq2ExK6AUUT5KxU7BYH6wW5dsSBUY4#z6MkqDYLpFyjvBCjaFWhijniEGAsejEXpScyH65WDHPTVUEd",
        "type": "Ed25519VerificationKey2018",
        "controller": "did:v1:test:nym:z6MkiUBCV4WG4ciU5vPq2ExK6AUUT5KxU7BYH6wW5dsSBUY4",
        "publicKeyBase58": "BmHJE1jJadiGTkg13ApsPAcsq9xgQZNcb5AaP1RSaFTF"
      }
    ],
    "capabilityInvocation": [
      {
        "id": "did:v1:test:nym:z6MkiUBCV4WG4ciU5vPq2ExK6AUUT5KxU7BYH6wW5dsSBUY4#z6MkiUBCV4WG4ciU5vPq2ExK6AUUT5KxU7BYH6wW5dsSBUY4",
        "type": "Ed25519VerificationKey2018",
        "controller": "did:v1:test:nym:z6MkiUBCV4WG4ciU5vPq2ExK6AUUT5KxU7BYH6wW5dsSBUY4",
        "publicKeyBase58": "51v9tpFpj5DzyRZ8LfzUF4vUdW474DwBb62aFMuRGFkg"
      }
    ],
    "capabilityDelegation": [
      {
        "id": "did:v1:test:nym:z6MkiUBCV4WG4ciU5vPq2ExK6AUUT5KxU7BYH6wW5dsSBUY4#z6Mkh5CRC7VMKZvFniVk8LtwZnM4wouEkkkV3NY8pnvs7qzy",
        "type": "Ed25519VerificationKey2018",
        "controller": "did:v1:test:nym:z6MkiUBCV4WG4ciU5vPq2ExK6AUUT5KxU7BYH6wW5dsSBUY4",
        "publicKeyBase58": "3cwNbsEuz2RngDf3Smw6igo58EdPLsW8MMdCzWxrCdDb"
      }
    ],
    "assertionMethod": [
      {
        "id": "did:v1:test:nym:z6MkiUBCV4WG4ciU5vPq2ExK6AUUT5KxU7BYH6wW5dsSBUY4#z6Mkg2qKhmsPyN91Sp2SeyBhCHQwMGDFu3A7K8MyEM7oKub4",
        "type": "Ed25519VerificationKey2018",
        "controller": "did:v1:test:nym:z6MkiUBCV4WG4ciU5vPq2ExK6AUUT5KxU7BYH6wW5dsSBUY4",
        "publicKeyBase58": "2aaH7XcxdpeYLKBjyQDrMBrwXgwQV9ukd7T3Q59nQgog"
      }
    ],
    "service": [
      {
        "id": "did:v1:test:nym:z6MkiUBCV4WG4ciU5vPq2ExK6AUUT5KxU7BYH6wW5dsSBUY4#service1",
        "serviceEndpoint": "https://agent.example.com",
        "type": "urn:AgentService"
      }
    ]
  },
  "proof": [
    {
      "type": "Ed25519Signature2018",
      "created": "2020-03-05T17:01:03Z",
      "creator": "did:v1:test:nym:z279yHL6HsxRzCPU78DAWgZVieb8xPK1mJKJBbP8T2CezuFY#z279yHL6HsxRzCPU78DAWgZVieb8xPK1mJKJBbP8T2CezuFY",
      "capability": "did:v1:uuid:c37e914a-1e2a-4d59-9668-ee93458fd19a",
      "capabilityAction": "write",
      "jws": "MOCKPROOF",
      "proofPurpose": "capabilityInvocation"
    },
    {
      "type": "Ed25519Signature2018",
      "created": "2020-03-05T17:01:06Z",
      "verificationMethod": "did:v1:test:nym:z6MkiUBCV4WG4ciU5vPq2ExK6AUUT5KxU7BYH6wW5dsSBUY4#z6MkiUBCV4WG4ciU5vPq2ExK6AUUT5KxU7BYH6wW5dsSBUY4",
      "proofPurpose": "capabilityInvocation",
      "capability": "did:v1:test:nym:z6MkiUBCV4WG4ciU5vPq2ExK6AUUT5KxU7BYH6wW5dsSBUY4",
      "capabilityAction": "create",
      "jws": "eyJhbGciOiJFZERTQSIsImI2NCI6ZmFsc2UsImNyaXQiOlsiYjY0Il19..5TcgiYsR0q92WCsCkUPMX5D6AZQH5-d_p3u6YMwAw7zypi8oQHrPGTnqzxMG_eJDVyHQN_o7ka5Fq853bgfDBw"
    }
  ]
}
```

This works fine without trying to add a service endpoint. 

Reproduction code: 

```
const v1 = require('did-veres-one');
const https = require('https');

const hostname = REDACTED;

async function test() {
    const httpsAgent = new https.Agent;

    const options = {mode: 'test', httpsAgent, hostname};
    const veresDriver = v1.driver(options);

    // Generate a new DID Document
    const didDocument = await veresDriver.generate({didType: 'nym', keyType: 'Ed25519VerificationKey2018'});

    // create service endpoint for did
    const serviceOptions = {
        fragment: "service1",
        endpoint: 'https://agent.example.com',
        type: 'urn:AgentService'
    };
    didDocument.addService(serviceOptions);

    // Log the new didDocument to the console.
    console.log('Generated:', JSON.stringify(didDocument, null, 2));

    const registrationResult = await veresDriver.register({didDocument});

    // Log the result of registering the didDoc to the VeresOne Test ledger
    console.log('Registered!', JSON.stringify(registrationResult, null, 2));
}

test();
```

I've also tried to register a simple DID first, then `observe()`, `addService()` and `update()` afterwards but it looked like a similar problem. 

I didn't see much documentation on adding service endpoints, just looking through the code mostly. Is there something obvious that I did incorrectly? 

As an aside, I noticed service `type` requires a `uri`. Is that specific to veres one? Didn't look like that was a requirement in the DID spec.

**Comment by dmitrizagidulin** [comment]
@AnthonyRonning You are correct, at the moment, Veres One does not allow service endpoints. (So what you're seeing is a validator error to that effect.)

In the medium to long term, the plan is to have an explicit 'allow' list of service endpoints (that will be curated by the Veres One community / governance structure) that are permitted in the did doc.

**Comment by AnthonyRonning** [comment]
Ah okay interesting. Thanks @dmitrizagidulin!
